- app/models/user.rb
- spec/models/user_spec.rb
I may have more substantive suggestions later.
> Simplify user full name method

- app/models/user.rb
- spec/models/user_spec.rb
Reverts umts/probable-engine#13
> Revert "Simplify user full name method"

- .travis.yml
> Removing rubocop from travis

- app/models/inventory.rb
- db/schema.rb
- spec/models/inventory_spec.rb
fixes #30 
@dfaulken might want to look as these mocks to see if they conform to his api
> Inventory api mocks

- app/models/incurred_incidental.rb
- app/models/note.rb
- db/migrate/20160411150352_create_notes.rb
- db/migrate/20160411151739_remove_notes_from_incurred_incidentals.rb
- db/schema.rb
- spec/factories/incurred_incidental.rb
- spec/factories/note.rb
- spec/models/incurred_incidental_spec.rb
- spec/models/note_spec.rb
Added new Notes table, which is polymorphic.  Removed old instances of 'note' column from Incurred Incidentals. Added specs for new notes.
> Add polymorphic Note table

- Gemfile
- Gemfile.lock
- app/views/rentals/_table.html.erb
1. Truncated Dates to 18 Chars - **Date is visible but time is not**
2. Converted Rental Amount to Currency
3. Centered all records
4. Capitalized and removed underscores from Status
> Implemented More User Friendly View of Rentals Table

- app/controllers/items_controller.rb
- app/views/rentals/_table.html.erb
- coverage/.last_run.json
- spec/controllers/items_controller_spec.rb
- spec/controllers/rentals_controller_spec.rb
- spec/models/rental_spec.rb
* Added some **coverage** to **rental_spec** and **items_controller_spec**
* **Fixed rental _table column** that was overwritten by previous commit
* **Refactored and improved error handling** of #create_item and #refresh_items methods in items_controller
* Commented out unused block of code in rentals_controller_spec
> Increasing coverage and minor edits

- app/controllers/rentals_controller.rb
- app/models/rental.rb
- app/views/rentals/_form.html.erb
- coverage/.last_run.json
- spec/spec_helper.rb
* Removed 'cart name' field from rental form ( which removed the final deleted_at: nil query )
* Item names are now pulled from the 'reservation' in the api and applied to new rentals
* Fixed back buttons in rental form
> Rental item bug fix and issue fix

- db/db_yml/incidental_types.yml
- db/seeds.rb
Added 4 default Incidental Types to seed file
- Towing
- Cleaning
- Late
- Minor Damages
> Default Incidental_Types

- app/views/incurred_incidentals/_form.html.erb
Updated link to creation of new rental on incurred incidental form
> Incurred Incidental Form Fix

- app/controllers/items_controller.rb
- coverage/.last_run.json
- spec/controllers/items_controller_spec.rb
Odd that these specs did not fail with [this pull request](https://github.com/umts/probable-engine/pull/101). Fixes the strings that were being modified.
> Fixes #130, modifying strings that are now frozen

- coverage/.last_run.json
- spec/models/item_spec.rb
Adds checks for
- A table containing no records
- A table containing one non-deleted record
- A table containing one deleted record
- A table containing one deleted, one non-deleted record.
> Adding additional item specs, for .deleted method

- app/assets/javascripts/global.js
- app/assets/stylesheets/rentals/rental_schedule.css
- app/views/rentals/_form.html.erb
Refactored inline styles from rental form to rental_schedule.css and added javascript to allow disclaimer to toggle correctly
> Refactor Inline styles and fixed disclaimer toggle

- app/assets/javascripts/global.js
> Added javascript for updating end time correctly on single day rental

- app/views/rentals/check_out.html.erb
Per #150 and code review discussion, adds popup warning user that they are about to process an early checkout
> Adding popup warning for early checkout

- app/models/rental.rb
- app/views/rentals/check_out.html.erb
- db/db_yml/item_types.yml
- spec/models/rental_spec.rb
Update pricing to reflect flat rates called for in #154.
> Fix golf cart pricing

- coverage/.last_run.json
- spec/controllers/reservations_controller_spec.rb
- Added rspec tests to improve reservation controller coverage to 100%
- Removed deprecation warnings from reservation controller specs
> Coverage increases, removing deprecation warnings

- app/controllers/application_controller.rb
> remove deprecation warning on 'nothing: true'

- app/views/departments/_form.html.erb
- app/views/departments/show.html.erb
- app/views/digital_signatures/show.html.erb
- app/views/financial_transactions/show.html.erb
- app/views/groups/_form.html.erb
- app/views/groups/show.html.erb
- app/views/incidental_types/_form.html.erb
- app/views/incidental_types/show.html.erb
- app/views/incurred_incidentals/_form.html.erb
- app/views/incurred_incidentals/show.html.erb
- app/views/item_types/_form.html.erb
- app/views/item_types/show.html.erb
- app/views/items/_form.html.erb
- app/views/items/new.html.erb
- app/views/items/new_item.html.erb
- app/views/items/show.html.erb
- app/views/rentals/drop_off.html.erb
- app/views/rentals/edit.html.erb
- app/views/rentals/no_show_form.html.erb
- app/views/rentals/pickup.html.erb
- app/views/rentals/show.html.erb
- app/views/reservations/_form.html.erb
- app/views/reservations/show.html.erb
- app/views/users/_form.html.erb
- app/views/users/show.html.erb
> change all back buttons

- Gemfile.lock
- coverage/.last_run.json
- spec/spec_helper.rb
> remove codeclimate start

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/environments/production.rb
- config/routes.rb
> Exception notifications

- app/controllers/rentals_controller.rb
- coverage/.last_run.json
don't know why it worked before, but I actually do need that. Paginate doesnt understand how without this.
> i do need that

- app/views/incurred_incidentals/index.html.erb
- app/views/incurred_incidentals/show.html.erb
- app/views/payment_tracking/index.html.erb
- app/views/rentals/_transaction_detail.html.erb
#232. Uses default date formatting in places where we either didn't format at all or formatted a little strangely, and adds currency formatting where it was missing.
> Simplify date formatting, format currency

- app/models/rental.rb
- coverage/.last_run.json
- spec/spec_helper.rb
> slight change here, more to come

- app/assets/stylesheets/ui.css
- app/controllers/departments_controller.rb
- app/models/user.rb
- app/views/departments/_form.html.erb
- app/views/users/_form.html.erb
- coverage/.last_run.json
- spec/controllers/users_controller_spec.rb
fixes #271 
fixes #260 
Users must have a department
> Dept mandatory

- db/seeds.rb
fixes #280 
also has something to do with #260
> Fix multi seed issue, and other seed issue to

- app/controllers/application_controller.rb
- app/views/errors/401.html.erb
> Nice you dont have an account with us page

- app/views/incidental_types/_form.html.erb
- app/views/incidental_types/show.html.erb
> add the fields to the form and the show page

- app/assets/javascripts/rentals/new.js.erb
- coverage/.last_run.json
> Saving dates

- Gemfile
- app/controllers/rentals_controller.rb
- app/models/rental.rb
- coverage/.last_run.json
- spec/controllers/rentals_controller_spec.rb
> Dropoff overdue rental

- app/models/groups_permission.rb
- app/models/groups_user.rb
> validate it things in adapters

- app/controllers/holds_controller.rb
- app/models/hold.rb
- coverage/.last_run.json
- spec/models/hold_spec.rb
> Holds canceling rentals

- app/assets/javascripts/rentals/index.js
Fixes #270 as per [documentation](https://fullcalendar.io/docs/mouse/eventClick/).
> fixed redirecting current window

- .rubocop.yml
- app/views/financial_transactions/index.html.erb
- app/views/incurred_incidentals/show.html.erb
- app/views/rentals/drop_off.html.erb
- app/views/rentals/invoice.html.erb
- app/views/rentals/no_show_form.html.erb
- app/views/rentals/pickup.html.erb
- app/views/rentals/show.html.erb
Fixes view errors introduced by #282
> Changes .amount to .initial_amount in views

- app/models/hold.rb
- coverage/.last_run.json
- spec/controllers/holds_controller_spec.rb
> add this test back in, it is still valid

- app/assets/javascripts/rentals/new.js.erb
fixes #307 
comments are possibly confusing
> correct a simple off by one

- app/assets/javascripts/global.js
- app/assets/stylesheets/rentals/rental_schedule.css
- app/controllers/item_types_controller.rb
- app/models/item.rb
- app/models/item_type.rb
- app/views/item_types/_form.html.erb
- app/views/item_types/index.html.erb
- app/views/item_types/show.html.erb
- app/views/items/index.html.erb
- app/views/items/show.html.erb
- app/views/rentals/_form.html.erb
- app/views/rentals/pickup.html.erb
- coverage/.last_run.json
- db/db_yml/item_types.yml
- db/migrate/20170418163930_drop_disclaimer_from_item_type.rb
- db/schema.rb
- spec/factories/item_type.rb
- spec/models/item_type_spec.rb
fixes #316 
fixes #319 kinda, its just a single checkbox but that might be fine, well see
> Remove disclaimer

- app/models/rental.rb
- config/environments/development.rb
> Automatic Incurred Incidental on Late Dropoffs

- app/views/rentals/show.html.erb
- coverage/.last_run.json
> Remove table tabs on rental#show

- app/controllers/rentals_controller.rb
- app/models/rental.rb
- coverage/.last_run.json
- spec/controllers/rentals_controller_spec.rb
- spec/models/rental_spec.rb
> Rental reservation event

- app/controllers/financial_transactions_controller.rb
- app/models/financial_transaction.rb
- app/models/rental.rb
- app/views/financial_transactions/_form.html.erb
- app/views/incurred_incidentals/show.html.erb
- app/views/payment_tracking/index.html.erb
- app/views/rentals/_transaction_detail.html.erb
- coverage/.last_run.json
- db/migrate/20170427164818_add_ref_to_payment.rb
- db/schema.rb
- spec/controllers/financial_transactions_controller_spec.rb
- spec/factories/financial_transaction.rb
- spec/factories/payment.rb
- spec/models/payment_spec.rb
- spec/models/rental_spec.rb
> Add ref to payment

- app/views/layouts/shared/_header.html.erb
Closes #346 
Serve oit googlebox over https instead of http.
> Mixed Content Issue

- app/views/damages/_form.html.erb
- app/views/departments/_form.html.erb
- app/views/financial_transactions/_form.html.erb
- app/views/groups/_form.html.erb
- app/views/holds/_form.html.erb
- app/views/incidental_types/_form.html.erb
- app/views/incurred_incidentals/_form.html.erb
- app/views/item_types/_form.html.erb
- app/views/items/_form.html.erb
- app/views/items/new_item.html.erb
- app/views/rentals/_form.html.erb
- app/views/rentals/drop_off.html.erb
- app/views/rentals/no_show_form.html.erb
- app/views/rentals/pickup.html.erb
- app/views/rentals/processing.html.erb
- app/views/users/_form.html.erb
Adds confirm popups to various submit buttons across app. 
#destroy methods already had confirm popups.
> General submit confirm popups

- app/views/item_types/new_item_type.html.erb
Continuation of #350 for #345, (confirm popup on item_type creation)
> Confirm popup for item_type create

- coverage/.last_run.json
- spec/controllers/damages_controller_spec.rb
- spec/factories/damage.rb
.95 - .48 = .47% more happiness
> Damages spec

- coverage/.last_run.json
- spec/controllers/home_controller_spec.rb
- spec/mailers/error_mailer_spec.rb
- spec/mailers/replacment_mailer_spec.rb
- spec/models/hold_spec.rb
- spec/spec_helper.rb
closes #364 
Coverage for mailers is now up to 100%
> Mailer tests

- app/views/rentals/processing.html.erb
in response to #368 which throws an error whenever this page is loaded.  this will allow it to work just not be able to search by item type.
> temporary fix to processing page

- app/controllers/rentals_controller.rb
- app/views/rentals/index.html.erb
- app/views/rentals/processing.html.erb
- coverage/.last_run.json
- spec/controllers/financial_transactions_controller_spec.rb
- spec/controllers/rentals_controller_spec.rb
- spec/mailers/error_mailer_spec.rb
- spec/mailers/replacment_mailer_spec.rb
fixes #368 
and a bug where the search form doesnt work at all, it just redirects to regular rentals index
> Fix processing page

- Gemfile
- Gemfile.lock
[Tom's changes to the aggressive inventory gem](https://github.com/umts/aggressive_inventory/pull/5) were merged into the master branch on umts, this PR simply changes the gemfile reference accordingly
> Gemfile Edit

- app/assets/javascripts/rentals/new.js.erb
- app/views/incurred_incidentals/index.html.erb
- config/environments/production.rb
This should fix the es6 compiling problem noted here #387 and allow us to update production (which is severely out of date at this point) so that we can have Calvin test the app.
Also fixed a depreciation that will be removed in 5.1 (as we will be updating to 5.1.4 shortly)
This is a short term solution if we intend on adding any es6 JS in the future as noted in #387
> Translate Rentals/New JS

- app/controllers/financial_transactions_controller.rb
- app/models/financial_transaction.rb
- app/views/financial_transactions/_form.html.erb
- app/views/financial_transactions/edit.html.erb
- app/views/financial_transactions/index.html.erb
- app/views/financial_transactions/new.html.erb
- app/views/financial_transactions/show.html.erb
- config/routes.rb
- spec/controllers/financial_transactions_controller_spec.rb
closes #392 
Fixed filter on index page (though with a workaround)
Removed unneeded actions and views
> Financial transactions fix

- app/controllers/rentals_controller.rb
- app/models/item_type.rb
- app/views/incidental_types/_form.html.erb
- app/views/rentals/_form.html.erb
Add table to Rentals form that displays the number of available items for each item type
> Show available rentals

- .codeclimate.yml
- app/assets/javascripts/financial_transactions/new.js
- app/models/damage.rb
- app/models/department.rb
- app/models/document.rb
- app/models/financial_transaction.rb
- app/models/hold.rb
- app/models/incurred_incidental.rb
- app/models/item.rb
- app/models/payment.rb
- app/models/rental.rb
- app/models/user.rb
- app/views/damages/_form.html.erb
- app/views/departments/_form.html.erb
- app/views/financial_transactions/_form.html.erb
- app/views/groups/_form.html.erb
- app/views/holds/_form.html.erb
- app/views/incidental_types/_form.html.erb
- app/views/incurred_incidentals/_form.html.erb
- app/views/item_types/_form.html.erb
- app/views/item_types/new_item_type.html.erb
- app/views/items/_form.html.erb
- app/views/rentals/_form.html.erb
- app/views/rentals/drop_off.html.erb
- app/views/rentals/pickup.html.erb
- app/views/users/_form.html.erb
- coverage/.last_run.json
- spec/controllers/users_controller_spec.rb
- spec/models/payment_spec.rb
closes #394 
- Added validations to models
- Made sure to enforce validations in views where necessary
- Cleaned up views a little
> Form and Model Validation Cleanup

- README.md
> added link to setup instructions to readme

- README.md
- app/mailers/error_mailer.rb
- app/views/layouts/application.html.erb
- config/application.rb
- config/database-example.yml
- config/database.travis.yml
- config/deploy.rb
- config/initializers/session_store.rb
I think this is why travis wasn't running earlier, not completely sure. Might want to double check.
> remove all instances of probable engine
